
services:
  backend:
    container_name: React-js
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app.db:/app/app.db
    ports:
      - "8000:8000"

  frontend:
    container_name: FastAPI
    build:
      context: ./frontend
      dockerfile: Dockerfile
    
    ports:
      - "3000:80"



